services:
  - type: web
    name: controlnetqr
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan migrate --force
    startCommand: php -S 0.0.0.0:10000 -t public

    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://controlnetqr.onrender.com

      - key: APP_KEY
        generateValue: true

      - key: PHP_CLI_SERVER_WORKERS
        value: 4

      - key: BCRYPT_ROUNDS
        value: 12

      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: debug

      # DATABASE (AIVEN)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-9283fc0-arizmendi-6993.h.aivencloud.com
      - key: DB_PORT
        value: 12429
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_SNtHHYyVrvncVUrzBcw
      - key: DB_SSL
        value: true

      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: database

      - key: CACHE_STORE
        value: database

      - key: MEMCACHED_HOST
        value: 127.0.0.1

      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: 6379

      # EMAIL
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: 21670012@itiguala.edu.mx
      - key: MAIL_PASSWORD
        value: gfqepuxsoasdhibp
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: 21670012@itiguala.edu.mx
      - key: MAIL_FROM_NAME
        value: Laravel
